# For Travis, we need a Node version and Linux image that work together. See:
# https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/4
dist: focal

language: node_js

sudo: false

-node_js:
  - 18

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0

install:
  - yarn install

script:
  - yarn test